language: python

matrix:
    include:
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: linux
          python: 3.7
          dist: xenial
          env: TOXENV=py37
        - os: linux
          python: 3.8-dev
          dist: xenial
          env: TOXENV=py38
        - os: linux
          python: 3.5
          env: TOXENV=docs
#        # Warning: Don't try to use code coverage analysis with pypy as it is insanely slow
#        - os: linux
#          python: pypy3
#          env: TOXENV=pypy3
#        # Latest Python 3.x from Homebrew
#        - os: osx
#          language: generic
#          env:
#            - TOXENV=py36
#            - BREW_INSTALL=python3

install:
  - pip install flake8 tox
#  - |
#    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
#      if [[ -n "$BREW_INSTALL" ]]; then
#        brew update
#        brew install "$BREW_INSTALL"
#      fi
#    fi

before_script:
  # stop the build if there are Python syntax errors or undefined names
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  if [[ $TOXENV == py37 ]]; then
    flake8 . --count --ignore=E252,W503 --max-complexity=26 --max-line-length=127 --show-source --statistics ;
  fi

script:
  - tox
